# Auto-generated Friends_localization_key
extends Node

enum Friends_localization_key {
	bootSplashHeader,
	titleScreenSubtitle,
	titleScreenBroughtBy,
	mainMenuNew,
	mainMenuLoad,
	mainMenuSettings,
	mainMenuExit,
	newSlot01,
	newSlot02,
	newSlot03,
	replaceSlot01,
	replaceSlot02,
	replaceSlot03,
	loadSlot01,
	loadSlot02,
	loadSlot03,
	settingsHeader01,
	audioMusic,
	audioSFX,
	audioUI,
	miscHeader,
	fullscreenTitle,
	languageTitle,
	backButton,
	pauseHeader,
	abilitiesTitle,
	mapTitle,
	pauseSettingsButton,
	pauseBackToTitle,
	hudTitle,
	hudAgain,
	abilityDoubleJump,
	abilityDash,
	abilitySlam,
	abilityRoll,
}
